apiVersion: batch/v1
kind: Job
metadata:
  name: next-chat-configurator
  labels:
    next: chat
    name: configurator
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"

spec:
  template:
    metadata:
      labels:
        next: chat
        name: configurator
    spec:
      containers:
      - name: next-chat-configurator
        image: "grayscale/next-chat-configurator:latest"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: sql__connectionString
            value: {{ .Values.sql.connectionString }}
      restartPolicy: Never        
