apiVersion: v1
kind: Service
metadata:
  name: next-chat-redis
  labels:
    next: chat
    name: redis
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    next: chat
    name: redis