apiVersion: v1
kind: Service
metadata:
  name: next-chat-server
  labels:
    next: chat
    name: server
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    next: chat
    name: server
