apiVersion: v1
kind: Service
metadata:
  name: next-chat-sql
  labels:
    next: chat
    name: sql
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    next: chat
    name: sql