CREATE TABLE IF NOT EXISTS `MessagesHistory` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `AuthorId` NVARCHAR(64) NOT NULL,
  `GroupId` NVARCHAR(64) NOT NULL,
  `Text` TEXT(16384) NOT NULL,
  `SendTime` DATETIME NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB